// Generates supabase/seed_steps.sql from lessons.js so the server knows every
// valid step and its maximum XP. Re-run after adding or changing lessons.
//   node scripts/gen-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
globalThis.window = {};
new Function("window", readFileSync(join(root, "lessons.js"), "utf8").replace(/^const py/m, "var py"))(globalThis.window);

const XP = { quiz: 5, predict: 5, code: 15, fill: 10, order: 10 }, BONUS = 20;
const rows = [];
for (const unit of window.UNITS)
  for (const lesson of unit.lessons) {
    lesson.steps.forEach((s, i) => XP[s.type] && !s.probe && rows.push(`('${lesson.id}:${i}', '${lesson.id}', ${XP[s.type]}, false)`));
    rows.push(`('${lesson.id}:bonus', '${lesson.id}', ${BONUS}, true)`);
  }
const sql = `-- GENERATED by scripts/gen-seed.mjs. Do not edit by hand.
insert into public.lesson_steps (step_key, lesson_id, max_xp, is_bonus) values
${rows.join(",\n")}
on conflict (step_key) do update set max_xp = excluded.max_xp, lesson_id = excluded.lesson_id, is_bonus = excluded.is_bonus;
`;
writeFileSync(join(root, "supabase", "seed_steps.sql"), sql);
console.log(`wrote ${rows.length} steps`);
